In [8]:

from eval_designs import *
from sequence_extraction import extract_sequences
from data_ingestor import ExperimentManager

from components import plot_rmsd_distributions_overlay, plot_violin_distributions, ViolinParams, plot_rmsd_summary_bars_seaborn

In [9]:
import sys, importlib
if 'components' in sys.modules:
    importlib.reload(sys.modules['components'])
else:
    import components

from components import plot_rmsd_distributions_overlay, plot_violin_distributions, ViolinParams

In [10]:
name = 'final_results'

In [11]:
#Import the experiments

em = ExperimentManager()
dfs: list[pd.DataFrame] = em.get_experiments(name=name)

In [12]:
combined = pd.concat(dfs, ignore_index=True)
 #! ! ! ! ! 
# Ensure that all dfs have exactly the same sample set. If one has samples that another doens't than these will be removed from the other too so that the comparison is fair. A unisue sample is identified by pdb_id + heavy_id, light_id, antigen_id , for one sample ther can exist multiple rows these are variants and are indicated by the sample_id column. Thus we group by the columns that identify a sample and then filter out samples that are not present in all experiments.
sample_id_cols = ['pdb_id', 'heavy_id', 'light_id', 'antigen_id']
sample_counts = combined.groupby(sample_id_cols)['experiment_id'].nunique()
valid_samples = sample_counts[sample_counts == len(dfs)].index
#only keep the rows that are in valid_samples
combined = combined.set_index(sample_id_cols).loc[valid_samples].reset_index()

In [13]:
#set display back to default
pd.reset_option('display.max_rows')
combined

,pdb_id,heavy_id,light_id,antigen_id,experiment_id,sample_id,sample_step,cdr_target,timestamp,reference_pdb_rpath,...,result_dir,uid,rmsd,ar,aar,ll,pll,ll_perplexity,pll_perplexity,sequences
0,1k4c,A,B,C,v2_base_cdrh3_testset_no_sb,0,100,H_CDR3,2025_08_19__00_59_41,0274_1k4c_A_B_C_2025_08_19__00_59_41/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v2_base_cdrh3_testset_no_sb___1k4c___A_B_C___0...,1.184414,6.0,0.666667,-29.961233,-15.160333,1.289054,5.389656,{'reference': {'chain_id_to_chain_idx': {'A': ...
1,1k4c,A,B,C,v2_base_cdrh3_testset_no_sb,1,100,H_CDR3,2025_08_19__00_59_41,0274_1k4c_A_B_C_2025_08_19__00_59_41/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v2_base_cdrh3_testset_no_sb___1k4c___A_B_C___1...,1.549009,4.0,0.444444,-30.792601,-19.931215,1.298168,9.157558,{'reference': {'chain_id_to_chain_idx': {'A': ...
2,1k4c,A,B,C,v2_base_cdrh3_testset_no_sb,2,100,H_CDR3,2025_08_19__00_59_41,0274_1k4c_A_B_C_2025_08_19__00_59_41/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v2_base_cdrh3_testset_no_sb___1k4c___A_B_C___2...,1.204182,6.0,0.666667,-26.597235,-13.118091,1.252824,4.295490,{'reference': {'chain_id_to_chain_idx': {'A': ...
3,1k4c,A,B,C,v2_base_cdrh3_testset_no_sb,3,100,H_CDR3,2025_08_19__00_59_41,0274_1k4c_A_B_C_2025_08_19__00_59_41/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v2_base_cdrh3_testset_no_sb___1k4c___A_B_C___3...,1.460452,5.0,0.555556,-34.336220,-20.906961,1.337744,10.206203,{'reference': {'chain_id_to_chain_idx': {'A': ...
4,1k4c,A,B,C,v2_base_cdrh3_testset_no_sb,4,100,H_CDR3,2025_08_19__00_59_41,0274_1k4c_A_B_C_2025_08_19__00_59_41/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v2_base_cdrh3_testset_no_sb___1k4c___A_B_C___4...,1.824736,5.0,0.555556,-29.881327,-18.344320,1.288182,7.677223,{'reference': {'chain_id_to_chain_idx': {'A': ...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13995,8dt3,H,L,C,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,3,100,H_CDR3,2025_09_02__16_11_32,0492_8dt3_H_L_C_2025_09_02__16_11_32/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,1.281436,3.0,0.250000,-18.137627,-20.580467,1.161715,5.556891,{'reference': {'chain_id_to_chain_idx': {'H': ...
13996,8dt3,H,L,C,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,4,100,H_CDR3,2025_09_02__16_11_32,0492_8dt3_H_L_C_2025_09_02__16_11_32/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,1.376567,1.0,0.083333,-19.377060,-21.134704,1.173676,5.819564,{'reference': {'chain_id_to_chain_idx': {'H': ...
13997,8dt3,H,L,C,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,5,100,H_CDR3,2025_09_02__16_11_32,0492_8dt3_H_L_C_2025_09_02__16_11_32/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,2.655383,2.0,0.166667,-20.075211,-27.416147,1.180468,9.822532,{'reference': {'chain_id_to_chain_idx': {'H': ...
13998,8dt3,H,L,C,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,6,100,H_CDR3,2025_09_02__16_11_32,0492_8dt3_H_L_C_2025_09_02__16_11_32/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,2.322995,3.0,0.250000,-22.185566,-28.104928,1.201237,10.402823,{'reference': {'chain_id_to_chain_idx': {'H': ...
13999,8dt3,H,L,C,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,7,100,H_CDR3,2025_09_02__16_11_32,0492_8dt3_H_L_C_2025_09_02__16_11_32/reference...,...,/simonvermeir/DGAD/models/diffab-main-edit-1/r...,v6_sims_pos_decay_aux_from_base_target_cdrh3_n...,2.247241,2.0,0.166667,-20.575050,-26.893662,1.185354,9.404032,{'reference': {'chain_id_to_chain_idx': {'H': ...

In [17]:
print('number of unique samples:', combined.groupby(sample_id_cols).ngroups)

# Group by experiment (support if multiple experiment_ids per df)
metrics = ['rmsd', 'aar', 'pll_perplexity']
#invert aar for given experiment_id (this was still old v new aar is 1-aar_old)
combined.loc[(combined['experiment_id'] == 'v2_base_cdrh3_testset_no_sb'), 'aar'] = 1 - combined.loc[(combined['experiment_id'] == 'v2_base_cdrh3_testset_no_sb'), 'aar']
combined.loc[(combined['experiment_id'] == 'base_from_scratch_target_cdrh3_sb_0-75_exp_testset'), 'aar'] = 1 - combined.loc[(combined['experiment_id'] == 'base_from_scratch_target_cdrh3_sb_0-75_exp_testset'), 'aar']

group = combined.groupby('experiment_id', dropna=False)[metrics]
agg = group.agg(['mean', 'std', 'min', 'max'])

agg

number of unique samples: 350

                                                        rmsd            \
                                                        mean       std
experiment_id
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  3.688575  2.478624
v2_base_cdrh3_testset_no_sb                         4.132883  3.712203
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  3.811970  2.802095
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  4.047634  3.403731
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  4.024854  3.660447

                                                                         \
                                                         min        max
experiment_id
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  0.566434  17.827850
v2_base_cdrh3_testset_no_sb                         0.595934  62.513936
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  0.569317  53.638887
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  0.578940  59.771904
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  0.576610  78.622965

                                                         aar                 \
                                                        mean       std  min
experiment_id
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  0.282266  0.132410  0.0
v2_base_cdrh3_testset_no_sb                         0.273661  0.135775  0.0
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  0.282792  0.135524  0.0
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  0.283003  0.136114  0.0
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  0.283110  0.135226  0.0

                                                          pll_perplexity  \
                                                      max           mean
experiment_id
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  0.875      10.467462
v2_base_cdrh3_testset_no_sb                         0.875       9.290927
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  0.875       9.035282
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  0.875       9.097102
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  0.875       9.063628

                                                                        \
                                                         std       min
experiment_id
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  3.752052  2.181129
v2_base_cdrh3_testset_no_sb                         3.331007  2.661920
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  3.246592  2.861294
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  3.268686  2.861294
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  3.248314  2.635115


                                                          max
experiment_id
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  32.817028
v2_base_cdrh3_testset_no_sb                         28.486908
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  31.114697
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  31.114697
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  30.542025

In [18]:
#determine percent differnce between  a and b

experiment_a = 'v2_base_cdrh3_testset_no_sb'
experiment_b = 'v6_sims_pos_aux_from_base_target_cdrh3_no_sb_testset_gsp-0-7_gsr-0-5_gss-1-0'
diff = (agg.loc[experiment_b] - agg.loc[experiment_a]) / agg.loc[experiment_a] * 100
diff

rmsd            mean    -7.764882
                std    -24.516647
                min     -4.466392
                max    -14.196913
aar             mean     3.336545
                std     -0.184998
                min           NaN
                max      0.000000
pll_perplexity  mean    -2.751556
                std     -2.534230
                min      7.489828
                max      9.224548
dtype: float64

In [ ]:
#print the same table but r@ounded to 3 decimals
#swap row 1 and row 2. So first comes [1] then [0], keep the rest the same
a = agg.iloc[[1,0] + list(range(2, len(agg)))]
#
a = a.round(3)
a

                                                     rmsd                \
                                                     mean    std    min
experiment_id
v2_base_cdrh3_testset_no_sb                         4.133  3.712  0.596
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  3.689  2.479  0.566
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  3.812  2.802  0.569
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  4.048  3.404  0.579
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  4.025  3.660  0.577

                                                              aar              \
                                                       max   mean    std  min
experiment_id
v2_base_cdrh3_testset_no_sb                         62.514  0.274  0.136  0.0
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  17.828  0.282  0.132  0.0
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  53.639  0.283  0.136  0.0
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  59.772  0.283  0.136  0.0
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  78.623  0.283  0.135  0.0

                                                          pll_perplexity  \
                                                      max           mean
experiment_id
v2_base_cdrh3_testset_no_sb                         0.875          9.291
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  0.875         10.467
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  0.875          9.035
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  0.875          9.097
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  0.875          9.064


                                                      std    min     max
experiment_id
v2_base_cdrh3_testset_no_sb                         3.331  2.662  28.487
base_from_scratch_target_cdrh3_sb_0-75_exp_testset  3.752  2.181  32.817
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_te...  3.247  2.861  31.115
v6_sims_pos_decay_aux_from_base_target_cdrh3_no...  3.269  2.861  31.115
v6_sims_pos_schedule_aux_from_base_target_cdrh3...  3.248  2.635  30.542

In [30]:

# give the latex just print 
print(a.to_latex())

\begin{tabular}{lrrrrrrrrrrrr}
\toprule
 & \multicolumn{4}{r}{rmsd} & \multicolumn{4}{r}{aar} & \multicolumn{4}{r}{pll_perplexity} \\
 & mean & std & min & max & mean & std & min & max & mean & std & min & max \\
experiment_id &  &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
v2_base_cdrh3_testset_no_sb & 4.133000 & 3.712000 & 0.596000 & 62.514000 & 0.274000 & 0.136000 & 0.000000 & 0.875000 & 9.291000 & 3.331000 & 2.662000 & 28.487000 \\
base_from_scratch_target_cdrh3_sb_0-75_exp_testset & 3.689000 & 2.479000 & 0.566000 & 17.828000 & 0.282000 & 0.132000 & 0.000000 & 0.875000 & 10.467000 & 3.752000 & 2.181000 & 32.817000 \\
v6_sims_pos_aux_from_base_target_cdrh3_no_sb_testset_gsp-0-7_gsr-0-5_gss-1-0 & 3.812000 & 2.802000 & 0.569000 & 53.639000 & 0.283000 & 0.136000 & 0.000000 & 0.875000 & 9.035000 & 3.247000 & 2.861000 & 31.115000 \\
v6_sims_pos_decay_aux_from_base_target_cdrh3_no_sb_testset_gsp-0-7_gsr-0-5_gss-1-0 & 4.048000 & 3.404000 & 0.579000 & 59.772000 & 0.283000 & 0.136000 & 0.000000 & 0.875000 & 9.097000 & 3.269000 & 2.861000 & 31.115000 \\
v6_sims_pos_schedule_aux_from_base_target_cdrh3_no_sb_testset_gsp-0-7_gsr-0-5_gss-1-0 & 4.025000 & 3.660000 & 0.577000 & 78.623000 & 0.283000 & 0.135000 & 0.000000 & 0.875000 & 9.064000 & 3.248000 & 2.635000 & 30.542000 \\
\bottomrule
\end{tabular}